# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: non-existent-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# # ---
# # apiVersion: v1
# # kind: Pod
# # metadata:
# #   name: pending-pod-2
# # spec:
# #   containers:
# #   - name: pending-container
# #     image: nginx
# #     volumeMounts:
# #     - name: pvc-volume
# #       mountPath: /usr/share/nginx/html
# #   volumes:
# #   - name: pvc-volume
# #     persistentVolumeClaim:
# #       claimName: non-existent-pvc
# #   restartPolicy: Always


##failing pod
---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod
spec:
  containers:
  - name: failing-container
    image: non-existent-image # This will cause the pod to fail
  restartPolicy: Always


---
apiVersion: v1
kind: Pod
metadata:
  name: successful-pod
spec:
  containers:
  - name: successful-container
    image: nginx
  restartPolicy: Always
