apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcrawler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcrawler
  template:
    metadata:
      labels:
        app: webcrawler
    spec:
      containers:
        - name: webcrawler
          image: nageshnode/webcrawler:webserver
          imagePullPolicy: Always
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "my-opentelemetry-collector.monitoring.svc.cluster.local:4317"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webcrawler-service
spec:
  selector:
    app: webcrawler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: LoadBalancer
